### ISSUE TITLE
Filter for 0 values drops filter

### ISSUE THREAD

**Issue by BrummbQ** [skynet2/ngx-odata#1]
Hello

This query doesn't set the expected filter string, instead it just drops the filter.
Should be `$filter=Property eq 0`

```
Query.create()
      .filter('Property', OperatorType.Eq, 0)
```

Greetings

**Comment by skynet2** [comment]
Hello @BrummbQ ,

Thank you for the bug report. 
Please check the latest version with fix. (1.0.1)

Query.create()
            .filter('Property', OperatorType.Eq, 0).compile()

Now works fine on my end.

Thanks,
Stas

**Comment by BrummbQ** [comment]
Thanks! Looks good to me too
