### ISSUE TITLE
filter doesn't play well with dates

### ISSUE THREAD

**Issue by BrummbQ** [skynet2/ngx-odata#2]
Hi again,

When filtering for dates, I have to use the filterComplex method:
```
query.filterComplex(`StartDate gt ${dateFilter.toISOString()}`)
```
Neither
```
query.filter('StartDate', OperatorType.Greater, dateFilter)
```
nor
```
query.filter('StartDate', OperatorType.Greater, dateFilter.toISOString())
```
produces a valid request. dateFilter is just a native Date object. It would be great if the library could format the date properly on its own.

**Comment by skynet2** [comment]
Hi @BrummbQ ,

Good idea, I like it.

Please check latest version 1.1.0.

I added ts-date package for formatting purposes https://github.com/standy/ts-date

Example : 
```
this.tempVar = Query.create().filter('StartDate', OperatorType.Greater, new Date()).compile();
this.tempVar3 = Query.create().filter('StartDate', OperatorType.Greater, new Date(), 'YYYY-MM- 
DD').compile();

Query.create().filter('StartDate', OperatorType.Greater, 123).compile();
this.tempVar2 = Query.create().filterComplex(`StartDate gt ${new Date().toISOString()}`).compile();
```

Please take a look :)

Thanks,
Stas

**Comment by BrummbQ** [comment]
Hi,
Is it possible to default here to datetime iso string formatting?
```
Query.create().filter('StartDate', OperatorType.Greater, new Date()) -> 2018-04-14 :(
```
At least in my case then it "just works" without additional formatting. But I'm no Odata expert, maybe different servers expect different formats.

*ah i see you are using formatDateIso, maybe formatDateTimeIso is a better fit

**Comment by skynet2** [comment]
Hi @BrummbQ ,

I see what you are talking about, probably, you are talking about formatLocalIso which suits more here.

Please check latest 1.1.1 

Thanks,
Stas

**Comment by BrummbQ** [comment]
yeah, this works

Thanks!
