### ISSUE TITLE
Upgrade to Angular 6

### ISSUE THREAD

**Issue by BrummbQ** [skynet2/ngx-odata#4]
Hello, me again

Your package still seems to use Angular 5. Can you upgrade to v6 please?

**Comment by skynet2** [comment]
Hi @BrummbQ ,

angular 5 is dev dependency, and it`s required only for playground (test) project.
There is no need to upgrade to v6, this will not impact library code. For the library, there is only 1 dep. ts-data.

Thanks,
Stas
